apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec:
      containers:
        - name: frontend-green
          image: frontend-green:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3200
          env:
            - name: VITE_API_URL
              value: "http://backend-service:5000"
